### ISSUE TITLE
[Bug]: Queue reordering

### ISSUE THREAD

**Issue by PowerUser64** [henniaufmrenni/boum#12]
### What happened?

When reordering the queue by pressing and holding queue items, it is possible to break the list in a way that the queue item will go into "hover mode" but won't actually be dragged around.

To do this, press and hold on a queue item for less than a second and then drag the queue item up or down. Notice that the queue item hovers above the rest of the queue items as if you could drag it somewhere, but it doesn't follow your finger. To fix this, simply drag up or down from any part of the page and the queue item will move up or down from its place, but won't go to where the drag is.

I would recommend changing the time you have to press and hold a queue item to move it to 0.5 seconds (as opposed to the current 1 second as I measure it), as that seems to be closer to what other apps do and would avoid potentially confusing users. Also, playing a haptic bump when the item is movable would be a nice touch.

*Note: I wasn't quite sure what to title this one, if you think of a better title, feel free to change it.*

### Version

v1.1.1

### What device and Android version are you seeing the problem on?

Google Pixel 3a / Android

### Understanding that boum is open-source software

- [X] I agree to follow this project's Code of Conduct

**Comment by henniaufmrenni** [comment]
Thank you for your report I, noticed this bug too. The library being used (`react-native-draggable-flatlist`) creates several probelm as seen also in #11. 
I guess long term an own implementation using `react-native-reanimated` and `react-native-gesture-handler` will be necessary and provide more flexibility.
