### ISSUE TITLE
[Bug]: boum steals "audio playback focus" when opened

### ISSUE THREAD

**Issue by PowerUser64** [henniaufmrenni/boum#40]
### What happened?

Steps to reproduce:
1. Play audio from another music app (eg. [Finamp](https://github.com/jmshrv/finamp) or Spotify)
2. Open boum

Playback of the other app will now pause, even though boum has not yet started playing.

See also: #39

### Version

boum v1.2.0

### What device and Android version are you seeing the problem on?

Google Pixel 3a / Android 12

### Understanding that boum is open-source software

- [X] I agree to follow this project's Code of Conduct

**Comment by henniaufmrenni** [comment]
Thank you for your report, I think the issue lies with the initialization of the previous queue which creates a new media session causing the other session to be paused. 
I'll check if there are other ways to initialize the queue to prevent this, if not I'll file an issue report on the underlying library.

**Comment by henniaufmrenni** [comment]
After reviewing the options possible to fix this I've decided to not fix this, because the only solution would be to remove the feature to continue the previous session.

**Comment by PowerUser64** [comment]
I don't know typescript, do you think this is a problem with react native track player? It might be worth filing a bug upstream.

Also, do you think it would be reasonable to add an option to move resume playback to a button on the home screen instead of what's happening right now?

**Comment by henniaufmrenni** [comment]
You mean a button like `Continue playing ${queue}` on the homescreen, so that only then queue will be initialized? Seems like a good idea that didn't occur to me before!

**Comment by PowerUser64** [comment]
Yeah, something like that is what I'm thinking - "Resume playback <album cover>" or like you said "Continue playing <queue>" (idk what <queue> would look like in text). Thanks for coming back to this!
