### ISSUE TITLE
[Bug]: opening ellipsis menu crashes boum

### ISSUE THREAD

**Issue by PowerUser64** [henniaufmrenni/boum#48]
### What happened?

Steps to reproduce:
1. Play some music (to get the player to appear at the bottom of the screen)
2. Open the now-playing screen by pressing the currently playing track at the bottom of the screen
3. Open the ellipsis menu in the upper-right-hand corner
4. Profit

boum should now crash.

### Version

boum v1.3.0

### What device and Android version are you seeing the problem on?

Google Pixel 3a / Android 12

### Understanding that boum is open-source software

- [X] I understand

**Comment by henniaufmrenni** [comment]
Can you check if this issue still exists in 1.3.0, because for me it doesn't?

**Comment by PowerUser64** [comment]
Yes, it does. I actually found this on 1.3.0, I guess I mistakenly typed 1.2.0 in the report.

**Comment by henniaufmrenni** [comment]
Unfortunatly I can't reproduce the issue, could you tell me which album/song causes the crash - if you prefer also via e-mail - so I can have a look?

**Comment by PowerUser64** [comment]
Well, it looks like this bug has magically stopped happening. I'll let you know if it crops back up, but it seems like this one is gone for now.
