### ISSUE TITLE
[Feat]: Display cards on library screen

### ISSUE THREAD

**Issue by PowerUser64** [henniaufmrenni/boum#49]
### Description

It would be really cool to have cards displayed below the headers on the library screen, almost like the home screen. For example, below the "Albums" header, there could be a side-scrolling list of albums. Just like how the home page has side-scrolling lists for random albums, latest albums, and more.

### Understanding that boum is open-source software

- [X] I understand

**Comment by henniaufmrenni** [comment]
If I understood you correctly it is a somewhat similar idea to what's implemented #56 song I'm closing this. If not feel free to reopen this issue.

**Comment by PowerUser64** [comment]
Yup, same idea. The only difference is I was thinking it would be for the Library screen.
