### ISSUE TITLE
[Feat]: Allow expanding lists on home page

### ISSUE THREAD

**Issue by PowerUser64** [henniaufmrenni/boum#50]
### Description

The lists of albums on the home page are really cool. A way to expand on the idea of these would be to turn the header above each list into a button that could open a full-screen version of the list.

Thoughts?

### Understanding that boum is open-source software

- [X] I understand

**Comment by henniaufmrenni** [comment]
Sounds like an neat idea, most of them use the same query - with different params - as the albums library screen so maybe we could navigate to the albums screen and set the query params to match?
