### ISSUE TITLE
[Bug]: 64bit release is identical to the regular one

### ISSUE THREAD

**Issue by Watn3y** [henniaufmrenni/boum#6]
### What happened?

The regular and the 64bit versions of boum on the GitHub releases page seem to be the same file.

#### SHA-256 hashes:

`e13b52698442e0750ff7e7c951be7d385d9a42250f1dc33330fec8c84f9de985  boum-1.1.0-arm64.apk`
`e13b52698442e0750ff7e7c951be7d385d9a42250f1dc33330fec8c84f9de985  boum-1.1.0.apk
`

I noticed this after boum failed to install on my Pixel 7 Pro since it only supports 64bit apps.

### Version

v1.1.0

### What device and Android version are you seeing the problem on?

Google Pixel 7 Pro cheetah TD1A.220804.031

### Understanding that boum is open-source software

- [x] I agree to follow this project's Code of Conduct

**Comment by henniaufmrenni** [comment]
Thank you for your report, the latest release should resolve this issue.
