### ISSUE TITLE
[Feat]: Download status indicator

### ISSUE THREAD

**Issue by faultydev** [henniaufmrenni/boum#68]
### Description

In my experience, it would be nice and useful to have an indicator of where the downloads are at.

This could be a page or a persistent notification that states where the downloads are currently at!

Thanks for considering!

### Understanding that boum is open-source software

- [X] I understand

**Comment by henniaufmrenni** [comment]
There is actually a screen where you can view the status of your downloads, it's under Settings->Go To Downloads.
Currently downloads aren't re-scheduable, but the download system is currently being reworked all together in #67.
I will keep this issue open however to track the implementation of a notification for downloads.
