### ISSUE TITLE
Consider Licensing

### ISSUE THREAD

**Issue by anthonylavado** [henniaufmrenni/boum#69]
Hi there 👋
First off, thank you for creating this app. I'm from the Jellyfin Core Team, and we love to see more clients become available for the platform.

Something I wanted to bring up early on (while you are still the only contributor), is to consider the licensing strategy for the app.

Because you will be publishing on the Apple App Store, you may want to consider a different license, such as the [Mozilla Public License 2.0](https://www.mozilla.org/en-US/MPL/2.0/FAQ/).

The waters are untested and not clear with App Store distribution restrictions and the GPLv3 (see [StackOverflow](https://opensource.stackexchange.com/questions/9500/is-apple-allowed-to-distribute-gplv3-licensed-software-through-its-ios-app-store)), but it was very clear back in earlier times with the GPLv2 (see [FSF.org](https://www.fsf.org/blogs/licensing/more-about-the-app-store-gpl-enforcement)).

There are a couple of different strategies to try and handle this gracefully. One is to dual-license the app. This requires explicit permission from all contributors, where one distribution is provided as GPL and the other as Mozilla Public License 2.0 (MPL). You can declare this once, and future contributions would be under those terms. Then, recipients of the code can choose which license they wish to obey. This is the strategy used by VLC. The MPL does allow distribution on the App Store, as it is more permissive on terms of distribution.

While you are the only contributor (and thus rights holder), you can also just choose to provide an exception to the license to Apple solely for distribution, but again this would require explicit consent on each commit/pull request from other contributors. This involves a lot more work.

The route I suggest considering is applying the MPL 2.0 to all code already contributed by yourself and for new contributions going forward, which simplifies the handling of distribution and licensing going forward. This is the route we've taken with our own [macOS Wrapper](https://github.com/jellyfin/jellyfin-server-macos) and [iOS App](https://github.com/jellyfin/jellyfin-expo).

Ultimately the choice is yours, and I am not a lawyer, so this should not be considered legal advice. That said, I want to make sure all projects that work with Jellyfin are as successful as possible, so I hope this helps.

**Comment by henniaufmrenni** [comment]
Thank you for opening this issue, I was indeed not aware that Apple is rejecting apps from the App Store when they're licensed under GPL. Relicensing definetly seems the most logical and as far as I understand the matter, issues like this were the exact reason why Mozilla created the MPL in the first place.
