### ISSUE TITLE
[Bug]: Downloads stall, unable to be cleared or restarted

### ISSUE THREAD

**Issue by shabby-goddess** [henniaufmrenni/boum#78]
### What happened?

Downloads sometimes appear to stall, especially when multiple albums are downloaded simultaneously. There is no option to clear or restart these downloads, as the 'delete' function is only accessible after downloads are complete. Clearing app cache does not resolve this issue.

![Screenshot_20230117-114657~2](https://user-images.githubusercontent.com/82282627/212997832-be970c0f-7a7d-45ce-88a5-27658f51173b.png)

### Version

1.5.0

### What device and Android version are you seeing the problem on?

Xperia 5 IV, Android 13

### Understanding that boum is open-source software

- [X] I understand

**Comment by henniaufmrenni** [comment]
Thank you for your report, version `1.6.0` featured a complete rewrite of the dowload logic, making it much more reliable and faster (the download speed in my testing is now limited by the network connection). You can als re-trigger downloads and cancel ongoing ones. The latest version `1.6.1` is available in the Play Store and in [Github Releases](https://github.com/henniaufmrenni/boum/releases)
