### ISSUE TITLE
[Feat]: Add drop shadow to top of screen to avoid contrast issues with status bar

### ISSUE THREAD

**Issue by PowerUser64** [henniaufmrenni/boum#88]
### Description

When light colors (like some album covers) pass under the android status bar, the app's background no longer contrasts with the light icons in the status bar, so it becomes hard to read. A way to fix this would be to add some sort of gradient to the top of the screen to provide a more consistent level of contrast.

### Understanding that boum is open-source software

- [X] I understand

**Comment by henniaufmrenni** [comment]
Good point, I think most consistent with [Android styling guidlines](https://developer.android.com/develop/ui/views/layout/edge-to-edge) would be to make it semi-transparent something like `rgba(0, 0, 0, 0.2)`.
